### PR TITLE
BeePMN 1.3 tests submission

### PR DESCRIPTION
**Pull request by aSegatto**

### CODE REVIEW

**Comment by tstephen** [comment]
Unfortunately this PR is conflicted and although it's a small problem at least at the moment I cannot resolve it because Github is not serving the patch file at https://github.com/bpmn-miwg/bpmn-miwg-test-suite/pull/746.patch

If you can send me the zip or a new PR I will resolve

**Comment by aturco80** [comment]
Alessandro S. is not in office today unfortunately. We are trying to recover the files from his pc. I will post the zip here if we find them. Otherwise, we will submit a new PR for the next meeting

**Comment by aturco80** [comment]
Found! 
[BeePMN 1.3.zip](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/files/1299740/BeePMN.1.3.zip)

**Comment by tstephen** [comment]
Thanks! Resolved manually by commit cfe053d78f492611444c66e746204bb86248d338

**Pull request closed without merging**
