### PR TITLE
Enterprise Architect 12.0.1207

### PR DESCRIPTION
**Pull request by bzinchenko**
Enterprise Architect 12.0.1207 roundtrip files

### CODE REVIEW

**Comment by falko** [comment]
Hi Boris,

could you also export a PNG/JPEG image or simply take a screenshot?

Cheers,
Falko

**Comment by bzinchenko** [comment]
Hello Falco

Images and PDFs added. Please merge. 

Thanks
Boris

**Comment by falko** [comment]
Thank you Boris!

**Comment by falko** [comment]
Here is the graphical diff:
http://bpmn-miwg.github.io/bpmn-miwg-tools/visual-test-result-comparison.html?tool=Enterprise%20Architect%2012.0.1207

**Pull request merged**
