### PR TITLE
Added C.4

### PR DESCRIPTION
**Pull request by SvenManierSAG**

### CODE REVIEW

**Comment by falko** [comment]
@SvenManierSAG  the PR adds Reference/Facilities.BPMN. Is that intended?

**Comment by SvenManierSAG** [comment]
No, its not intended. Can you delete this one or is a new PR necessary?

**Comment by falko** [comment]
@SvenManierSAG it would speed up things if you could simply add a commit to your branch where you delete it. The pull request will update automatically. When I merge the PR, both commits will be squashed into one, so the file never hits the MIWG repo. ;-)

**Comment by SvenManierSAG** [comment]
Its deleted

**Pull request merged**
