### PR TITLE
Adding W4 C files

### PR DESCRIPTION
**Pull request by benmichel**
Adding import, export and roundtrip from W4 BPMN+ composer for files :
- C.1.0
- C.1.1
- C.2.0
- C.3.0

### CODE REVIEW

**Comment by falko** [comment]
Hi Ben,

thank you for the new results. Your pull request also adds an XSD to the reference folder. Is that an addition to any of the references? If so, could we rename it to mark to which reference it belongs?

Cheers,
Falko

**Comment by benmichel** [comment]
Hi Falko,

Yes, the xsd file is imported by bpmn C.1.1.bpmn, renaming it implies modifiying it's reference in the "location" attribute of the "import" element in C.1.1.bpmn. I can do it, commit it and recreate the pull request if you wish

Benjamin

**Comment by falko** [comment]
I just checked and we already have three other submissions for C.1.1 and I don't want to force resubmissions on these vendors. Let's leave it as is.

**Comment by falko** [comment]
Could you also double check your submission of category A

**Comment by benmichel** [comment]
I don't know what is counted for category A. The only thing that is missing for us for Category A is the export for A.1.1 since we can't draw vertical lane for now. It may be this ?

**Comment by falko** [comment]
Well, then the count makes sense, as an export test contains a BPMN file and a PNG.

**Comment by benmichel** [comment]
oh yes that's right !

**Pull request merged**
